[package]
authors = ["Jan <jankaul@mailbox.org>"]
edition = "2021"
name = "weblab-interpreter"
version = "0.2.7"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
futures = "0.3.17"
js-sys = "0.3.55"
string_cache = "0.8.2"
swc = "0.79.0"
swc_atoms = "0.2.9"
swc_ecma_ast = "0.56.0"
swc_ecma_parser = "0.76.0"
swc_ecma_visit = "0.42.0"
parking_lot_core = "=0.8.0"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
wasm-bindgen-test = "0.3.28"
regex = "1.5.4"
lazy_static = "1.4.0"
ahash = "0.7.6"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
features = [
    "console",
    "Request",
    "Response",
    "Window",
    "Url",
    "Blob",
    "HtmlElement",
]
version = "0.3.55"

[dependencies.swc_common]
features = ["tty-emitter"]
version = "0.14.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.28"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
