[package]
authors = ["Jan <jankaul@mailbox.org>"]
edition = "2021"
name = "weblab-interpreter"
version = "0.2.11"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
futures = "0.3.21"
js-sys = "0.3.56"
string_cache = "0.8.3"
swc = "0.138.0"
swc_atoms = "0.2.9"
swc_ecma_ast = "0.68.3"
swc_ecma_parser = "0.91.11"
swc_ecma_visit = "0.54.0"
parking_lot_core = "=0.8.0"
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
wasm-bindgen-test = "0.3.29"
regex = "1.5.4"
lazy_static = "1.4.0"
ahash = "0.7.6"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
features = [
    "console",
    "Request",
    "Response",
    "Window",
    "Url",
    "Blob",
    "HtmlElement",
]
version = "0.3.56"

[dependencies.swc_common]
features = ["tty-emitter"]
version = "0.17.9"

[dev-dependencies]
wasm-bindgen-test = "0.3.29"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
